voiced_voice011_0:
  age: 55
  gender: male
  label: pathological
  speaker_id: voice011
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice011.wav
  texts:
  - age=55; gender=male
voiced_voice016_0:
  age: 50
  gender: female
  label: pathological
  speaker_id: voice016
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice016.wav
  texts:
  - age=50; gender=female
voiced_voice024_0:
  age: 38
  gender: male
  label: normal
  speaker_id: voice024
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice024.wav
  texts:
  - age=38; gender=male
voiced_voice035_0:
  age: 48
  gender: male
  label: pathological
  speaker_id: voice035
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice035.wav
  texts:
  - age=48; gender=male
voiced_voice046_0:
  age: 43
  gender: female
  label: pathological
  speaker_id: voice046
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice046.wav
  texts:
  - age=43; gender=female
voiced_voice125_0:
  age: 36
  gender: female
  label: normal
  speaker_id: voice125
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice125.wav
  texts:
  - age=36; gender=female
voiced_voice135_0:
  age: 25
  gender: female
  label: pathological
  speaker_id: voice135
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice135.wav
  texts:
  - age=25; gender=female
voiced_voice162_0:
  age: 55
  gender: female
  label: pathological
  speaker_id: voice162
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice162.wav
  texts:
  - age=55; gender=female
voiced_voice166_0:
  age: 50
  gender: female
  label: pathological
  speaker_id: voice166
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice166.wav
  texts:
  - age=50; gender=female
voiced_voice181_0:
  age: 29
  gender: female
  label: normal
  speaker_id: voice181
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice181.wav
  texts:
  - age=29; gender=female
voiced_voice183_0:
  age: 22
  gender: female
  label: normal
  speaker_id: voice183
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice183.wav
  texts:
  - age=22; gender=female
voiced_voice187_0:
  age: 49
  gender: female
  label: pathological
  speaker_id: voice187
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice187.wav
  texts:
  - age=49; gender=female
voiced_voice190_0:
  age: 38
  gender: female
  label: pathological
  speaker_id: voice190
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice190.wav
  texts:
  - age=38; gender=female
voiced_voice203_0:
  age: 22
  gender: female
  label: normal
  speaker_id: voice203
  text_keys:
  - /home/storage/voiced/voice-icar-federico-ii-database-1.0.0/voice203.wav
  texts:
  - age=22; gender=female
