FROM pytorch/pytorch:2.2.0-cuda11.8-cudnn8-devel

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    libsndfile-dev \
    unzip \
    wget

RUN pip install pipenv