muscle_tension:
  female:
    age_stats:
      max: 50
      mean: 46.75
      min: 38
      std: 5.852349955359813
    total: 4
organic_inflammatory:
  female:
    age_stats:
      max: 43
      mean: 43
      min: 43
      std: null
    total: 1
  male:
    age_stats:
      max: 55
      mean: 51.5
      min: 48
      std: 4.949747468305833
    total: 2
organic_neuro_muscular:
  female:
    age_stats:
      max: 55
      mean: 40
      min: 25
      std: 21.213203435596427
    total: 2
